---
endpoint_type: internal
cloud: default

image:
  repository: quay.io/niedbalski/openstack-exporter-linux-amd64
  tag: master
  pullPolicy: Always

serviceMonitor:
  interval: 1m
  scrapeTimeout: 30s
